source 'https://api.berkshelf.com'

cookbook 'apt', '= 2.3.8'
cookbook 'locale', github: 'ww24/locale', branch: 'fix'
cookbook 'apache2', github: 'ww24/apache2', branch: 'fix'
cookbook 'mysql', '= 5.3.4'
cookbook 'memcached', '= 1.7.2'
cookbook 'php', '= 1.4.6'
cookbook 'composer', '= 1.0.0'
cookbook 'git', '= 4.0.0'
